executed with `VMError("validator_disagrees call 0")`
