executed with `ContractError("validator_disagrees call 0")`
